yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]  # Роутинг запросов приложения 'About'

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),

]  # Роутинг запросов приложения Posts

yatube/users/urls.py
from django.contrib.auth.views import PasswordResetView, LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('signup/',
         views.SignUp.as_view(template_name='users/signup.html'),
         name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('reset_password/', PasswordResetView.as_view(
         template_name='users/reset_password.html'),
         name='reset_password'),
]  # Роутинг запросов приложения Users

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('django.contrib.auth.urls')),
]

yatube/posts/models.py
from django.contrib.auth.models import User
from django.db import models


class Group(models.Model):
    """ ORM модель групп """
    title = models.CharField('Название группы', max_length=200)
    slug = models.SlugField('URL адрес', default='some string',
                            unique=True)
    description = models.TextField('Описание группы',
                                   max_length=10000,
                                   default='some string', )

    class Meta:
        """ Отображение в админке """
        verbose_name = 'Группы'
        verbose_name_plural = 'Группы'
        ordering = ('-title',)

    def __str__(self):
        return self.title


class Post(models.Model):
    """ ORM модель постов """
    text = models.TextField('Текст поста', max_length=15000)
    pub_date = models.DateTimeField('Дата публикации',
                                    auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='posts',
                               verbose_name='Автор')
    group = models.ForeignKey(Group, blank=True, null=True,
                              on_delete=models.SET_NULL,
                              related_name='posts',
                              verbose_name='Группа')

    class Meta:
        """ Отображение в админке """
        ordering = ('-pub_date',)
        verbose_name_plural = 'Сортировка по дате публикации'

    def __str__(self):
        return self.text[0:30]

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    """ Форма создание поста """
    class Meta:
        model = Post
        fields = ('text', 'group')
        labels = {
            'name': 'Author',
        }
        help_texts = {
            'text': 'Текст поста',
            'group': 'Название группы',
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    """ Форма для создания пользователя """
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    """ Шаблон раздела 'Об Авторе' """

    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    """ Шаблон раздела 'Технологии' """

    template_name = 'about/tech.html'

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect

from .models import Group, Post, User
from .forms import PostForm
from .utils import paginator


def index(request):
    """ Главная страница """
    post_list = Post.objects.select_related('author', 'group').all()
    page_obj = paginator(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """ Страница группы """
    group_with_slug = get_object_or_404(Group, slug=slug)
    post_list = group_with_slug.posts.select_related('author').all()
    page_obj = paginator(request, post_list)
    context = {
        'page_obj': page_obj,
        'group': group_with_slug,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """ Страница автора поста """
    user_of_profile = get_object_or_404(User, username=username)
    post_list = user_of_profile.posts.select_related('group').all()
    page_obj = paginator(request, post_list)
    context = {
        'page_obj': page_obj,
        'usermodel': user_of_profile,
        'post_list': post_list  # Отображение числа постов пользователя
    }

    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """ Подробное чтение поста """
    get_post = get_object_or_404(Post, id=post_id)
    onepost = get_post
    context = {
        'onepost': onepost,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """ Функция создания поста """
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():  # Валидация формы создания поста
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', username=request.user.username)
        return render(request, 'posts/profile.html', {'form': form})
    form = PostForm()

    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    """ Редактирование поста """
    post = get_object_or_404(Post, id=post_id)  # Получения поста
    if post.author != request.user:  # Проверка прав для редактирования
        return redirect('posts:post_detail', post_id=post_id)
    if request.method == 'POST':
        post_edited = PostForm(instance=post, data=request.POST)
        post_edited.save()
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(instance=post)
    contex = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', contex)

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    """ Стандартная форма создания пользователя """
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<div class="container py-5">
  <h1>Привет, я автор</h1>
  <p>
    Тут я размещу информацию о себе, используя свои умения верстать.
    Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста.
  </p>
</div>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
<div class="container py-5">
  <h1>Вот что я умею</h1>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  <article class="container py-5">
    <p>Текст страницы "Технологии"</p>
  </article>
</div>
{% endblock %} 

yatube/templates/base.html
{% load static %}
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" src="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" src="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" src="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" src="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header> 
    <main>
      {% block content %}
      {% endblock %}
    </main>
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}  
    </footer> 
  </body>
</html>

yatube/templates/includes/error_form.html
{% load user_filters %}
<!-- Цикл для отображения ошибок при заполнении форм-->
{% if form.errors %}
 {% for field in form %} 
   {% for error in field.errors %}            
     <div class="alert alert-danger">
      {{ error|escape }}
     </div>
   {% endfor %}
 {% endfor %}
 {% for error in form.non_field_errors %}
   <div class="alert alert-danger">
     {{ error|escape }}
   </div>
 {% endfor %}
{% endif %}

yatube/templates/includes/footer.html
<!-- Футер с контекст-процессором -->
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/form.html
{% load user_filters %}
<!-- Форма -->
{% for field in form %} 
  <div class="form-group row my-3">
  <label for="{{ field.id_for_label }}">
  {{ field.label }}
  {% if field.field.required %}
    <span class="required text-danger">*</span>
  {% endif %}
  </label>
<!-- CSS Фильтр из модуля Core -->
  {{ field|addclass:'form-control' }}
    {% if field.help_text %}
    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
      {{ field.help_text|safe }}
    </small>
    {% endif %}
   </div>
{% endfor %} 

yatube/templates/includes/header.html
{% load static %}
<!-- Хедер -->
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    <ul class="nav nav-pills">
      <!-- Навигация по сайту -->
      {% with request.resolver_match.view_name as view_name %}  
      <li class="nav-item"> 
        <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
         href="{% url 'about:author' %}">Об авторе</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" 
         href="{% url 'about:tech' %}">Технологии</a>
      </li>
      <!-- Проверка авторизации пользователя -->
      {% if request.user.is_authenticated %}
      <li class="nav-item"> 
        <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
         href="{% url 'posts:post_create' %}">Новая запись</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == 'users:reset_password' %}active{% endif %}
         " href="{% url 'users:reset_password' %}">Изменить пароль</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}" 
         href="{% url 'users:logout' %}">Выйти</a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-light {% if view_name  == 'posts:profile' %}active{% endif %}"
        <a href="{% url 'posts:profile' user.username %}">Пользователь: {{ user.username }}</a>
      </li>
      {% else %} 
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" 
         href="{% url 'users:login' %}">Войти</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}" 
         href="{% url 'users:signup' %}">Регистрация</a>
      </li>
      {% endif %} 
      {% endwith %} 
    </ul>
  </div>
</nav>      

yatube/templates/posts/create_post.html
<!-- Страница создания и редактирования постов-->
{% extends "base.html" %}
{% block title %}
  <!-- Проверка наличия у поста id -->
  {% if form.instance.id %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock%}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          <!-- Проверка наличия у поста id -->
          {% if form.instance.id %}
            Редактировать пост
          {% else %}
            Новый пост
          {% endif %}
        </div>
        <div class="card-body">
          {% include 'includes/error_form.html' %}
          {% if form.instance.id %}
            <form method="POST" action="{% url 'posts:post_edit' form.instance.id %}">
          {% else %}
            <form method="POST" action="{% url 'posts:post_create' %}">
          {% endif %}
            {% csrf_token %}
            {% include 'includes/form.html' %}
              <div class="d-flex justify-content-end">
                <button type="submit" value="Submit" class="btn btn-primary">
                  <!-- Проверка наличия у поста id -->
                  {% if form.instance.id %}
                    Добавить
                  {% else %}
                    Сохранить
                  {% endif %}
                </button>
              </div>
            </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
<!-- Страница группы -->
{% extends "base.html" %}
{% block title %}{{ group.title }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>
      {{ group.title }} 
    </h1>
    <p>{{ group.description|linebreaksbr }}</p>
    <!-- Отрисовка всех постов группы -->
    {% for post in page_obj %}
      {% include 'posts/includes/postcard.html' with group_page=True %}
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %} 
  </div>  
{% endblock %} 

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<!-- Шаблон Paginator -->
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/includes/postcard.html
<!-- Карточка поста -->
<article>
  <ul>
    <li>
      <a>
        Автор: {{ post.author }}
      </a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
    {% if not profile %}
      <li>
        <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
      </li>
    {% endif %}
  </ul>
  <p>
    {{ post.text|linebreaksbr }}
  </p>
  <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
  {% if not group_page %}
    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">
        все записи группы
      </a>
    {% else %}
      <span style='color: red'>
        Этой публикации нет ни в одном сообществе.
      </span>
    {% endif %}
  {% endif %}
</article>

yatube/templates/posts/index.html
<!-- Главная страница Yatube -->
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Главная страница Yatube</h1> 
    {% for post in page_obj %}
      {% include 'posts/includes/postcard.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %} 

yatube/templates/posts/post_detail.html
<!-- Подробная информация о посте -->
{% extends "base.html" %}
{% block title %} Детали поста {% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ onepost.pub_date }}
        </li>
        <!-- Проверяем есть ли у поста группа-->
        {% if onepost.group %}
          <li class="list-group-item">
            Группа: {{ onepost.group.title }}
            <a href="{% url 'posts:group_list' onepost.group.slug %}">
              все записи группы
            </a>
          </li>
        {% else %}
          <span style='color: red'>
            Этой публикации нет ни в одном сообществе.
          </span>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ onepost.author }}
        </li>
        <li class="list-group-item">
          <!-- Ссылка на профиль автора поста -->
          <a href="{% url 'posts:profile' onepost.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>
        {{ onepost.text }}
      </p>
    </article>
    <!-- Проверка прав на редактирование поста  -->
    {% if request.user == onepost.author %}
      <a href="{% url 'posts:post_edit' onepost.id %}">
        Редактировать пост
      </a>
    {% endif %}
  </div>
{% endblock %}

yatube/templates/posts/profile.html
<!-- Профайл пользователя -->
{% extends "base.html" %}
{% block title %}Профайл пользователя {{ usermodel.username }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Страница пользователя {{ usermodel.username }}</h1>
    <h4>
      Всего постов автора: <span>{{ post_list|length }}</span>
    </h4>
    {% for post in page_obj %}
      {% include 'posts/includes/postcard.html' with profile=True %}
      {% if not forloop.last %}<hr>
      {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> 
    </div> 
  </div> 
</div> 
{% endblock %} 

yatube/templates/users/login.html
<!-- Форма авторизации на сайте -->
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Войти на сайт
      </div>
      <div class="card-body">
        <!-- Форма обработки ошибок при вводе-->
        {% include 'includes/error_form.html' %}
        <form method="post" {% if action_url %} action="{% url action_url %}" {% endif %}>
          {% csrf_token %}
          <!-- Форма авторизации -->
          {% include 'includes/form.html' %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary" href="{% url 'posts:index' %}">
              Войти
            </button>
            <!-- Ссылка на восстановление пароля -->
            <a href="{% url 'users:reset_password' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/reset_password.html
{% extends "base.html" %}
{% block title %} Смена пароля{% endblock title %}
{% block content %}
<div class="container py-5">
    <h2> Сменить пароль </h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Подтвердить</button>
    </form>
</div>
{% endblock %}

yatube/templates/users/signup.html
<!-- Форма регистрации на сайте -->
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
            <!-- Форма обработки ошибок при вводе-->
            {% include 'includes/error_form.html' %}
              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
                <!-- Форма регистрации -->
              {% include 'includes/form.html' %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> 
        </div> 
      </div> 
  </div> 
{% endblock %}